[project]
name = "vispipe"
version = "1.0.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Joshua Gramm", email = "joshua.d.gramm@erdc.dren.mil" }
]
requires-python = ">=3.9"
dependencies = [
    "absl-py",
    "accessible-pygments",
    "adcircpy",
    "alabaster",
    "annotated-types",
    "anyio",
    "appdirs",
    "argon2-cffi",
    "argon2-cffi-bindings",
    "arrow",
    "asttokens",
    "astunparse",
    "async-lru",
    "attrs",
    "babel",
    "backcall",
    "bcrypt",
    "beautifulsoup4",
    "bleach",
    "cachetools",
    "certifi",
    "cffi",
    "cftime",
    "charset-normalizer",
    "click",
    "click-plugins",
    "cligj",
    "colorama",
    "comm",
    "contourpy",
    "cryptography",
    "cupy-cuda11x",
    "cycler",
    "cython",
    "dataretrieval",
    "debugpy",
    "decorator",
    "defusedxml",
    "deprecated",
    "docutils",
    "erddapy",
    "executing",
    "fastjsonschema",
    "fastrlock",
    "filelock",
    "fiona",
    "flatbuffers",
    "fonttools",
    "fortls",
    "fqdn",
    "gast",
    "geopandas",
    "google-auth",
    "google-auth-oauthlib",
    "google-pasta",
    "grpcio",
    "h11",
    "h5py",
    "haversine",
    "html5lib",
    "httpcore",
    "httpx",
    "idna",
    "imagesize",
    "importlib-resources",
    "iniconfig",
    "ipykernel",
    "ipython",
    "ipywidgets",
    "isoduration",
    "jedi",
    "jinja2",
    "json5",
    "jsonpointer",
    "jsonschema",
    "jsonschema-specifications",
    "jupyter",
    "jupyter-client",
    "jupyter-console",
    "jupyter-core",
    "jupyter-events",
    "jupyter-lsp",
    "jupyter-server",
    "jupyter-server-terminals",
    "jupyterlab",
    "jupyterlab-pygments",
    "jupyterlab-server",
    "jupyterlab-widgets",
    "keras",
    "kiwisolver",
    "libclang",
    "limits",
    "littleutils",
    "lxml",
    "markdown",
    "markupsafe",
    "matplotlib",
    "matplotlib-inline",
    "mistune",
    "ml-dtypes",
    "mpmath",
    "nbclient",
    "nbconvert",
    "nbformat",
    "nest-asyncio",
    "netcdf4",
    "networkx",
    "notebook",
    "notebook-shim",
    "numpy",
    "numpydoc",
    "oauthlib",
    "opt-einsum",
    "overrides",
    "packaging",
    "pandas",
    "pandocfilters",
    "paramiko",
    "parso",
    "pickleshare",
    "pillow",
    "pint",
    "platformdirs",
    "plotly",
    "pluggy",
    "pooch",
    "prometheus-client",
    "prompt-toolkit",
    "protobuf",
    "psutil",
    "pure-eval",
    "pyasn1",
    "pyasn1-modules",
    "pycparser",
    "pydantic",
    "pydantic-core",
    "pydata-sphinx-theme",
    "pygments",
    "pymupdf",
    "pymupdfb",
    "pynacl",
    "pyparsing",
    "pyproj",
    "pytest",
    "python-dateutil",
    "python-json-logger",
    "pytz",
    "pywin32",
    "pywinpty",
    "pyyaml",
    "pyzmq",
    "qtconsole",
    "qtpy",
    "referencing",
    "requests",
    "requests-oauthlib",
    "rfc3339-validator",
    "rfc3986-validator",
    "rpds-py",
    "rsa",
    "scipy",
    "searvey",
    "send2trash",
    "shapely",
    "six",
    "sniffio",
    "snowballstemmer",
    "sorcery",
    "soupsieve",
    "sphinx",
    "sphinx-autodoc-typehints",
    "sphinxcontrib-applehelp",
    "sphinxcontrib-devhelp",
    "sphinxcontrib-htmlhelp",
    "sphinxcontrib-jsmath",
    "sphinxcontrib-qthelp",
    "sphinxcontrib-serializinghtml",
    "stack-data",
    "stormevents",
    "sympy",
    "tabulate",
    "tenacity",
    "tensorboard",
    "tensorboard-data-server",
    "tensorflow",
    "tensorflow-estimator",
    "tensorflow-intel",
    "tensorflow-io-gcs-filesystem",
    "termcolor",
    "terminado",
    "tinycss2",
    "torch",
    "torchaudio",
    "torchvision",
    "tornado",
    "tqdm",
    "traitlets",
    "typepigeon",
    "typing-extensions",
    "tzdata",
    "uri-template",
    "urllib3",
    "utm",
    "wcwidth",
    "webcolors",
    "webencodings",
    "websocket-client",
    "werkzeug",
    "widgetsnbextension",
    "wrapt",
    "xarray",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
